version: '3.8'
services:
  blog-api:
    image: blog-api:latest
    container_name: blog-api
    ports:
      - "8080:8080"
    volumes:
      - ./.env.sample:/app/.env
    restart: always
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: blog
    volumes:
      - compose-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  compose-postgres-data: 


